### ISSUE TITLE
Missing dependency in wheel uploaded to pypi (v20.4.1)

### ISSUE THREAD

**Issue by nehaljwani** [Instagram/LibCST#279]
```
 ❯❯❯ pip install monkeytype
Collecting monkeytype
  Downloading MonkeyType-20.4.1-py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 18 kB/s 
Collecting mypy-extensions
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Installing collected packages: mypy-extensions, monkeytype
Successfully installed monkeytype-20.4.1 mypy-extensions-0.4.3
 ❯❯❯ monkeytype --help
Traceback (most recent call last):
  File "/tmp/nwani_1585950476/dev/bin/monkeytype", line 5, in <module>
    from monkeytype.cli import entry_point_main
  File "/tmp/nwani_1585950476/dev/lib/python3.8/site-packages/monkeytype/cli.py", line 16, in <module>
    from libcst import parse_module
ModuleNotFoundError: No module named 'libcst'
 ❯❯❯                          
```

**Comment by carljm** [comment]
Hi, this is a problem with MonkeyType's new release, not a problem with LibCST :) I will make a new 20.4.2 release that fixes the missing dependency. Thanks for the report!
