### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#294]
There are 6 tests failing on rev `93a389b8d9e707fb1f93a9e22efe4be11375361e` (`test_calculate_module_4` ... `test_calculate_module_8` and `test_codemod_formatter_error_input` - although this last one might be a problem with my environment somehow?)

Repro: `python -m tox -e py37`

```
======================================================================
FAIL: test_calculate_module_4 (libcst.codemod.tests.test_cli.TestPackageCalculation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\zsolz\LibCST\libcst\testing\utils.py", line 89, in new_test
    return member(self, *data)
  File "C:\Users\zsolz\LibCST\libcst\codemod\tests\test_cli.py", line 46, in test_calculate_module
    self.assertEqual(_calculate_module(repo_root, filename), module)
AssertionError: None != 'file'
```

```
======================================================================
FAIL: test_codemod_formatter_error_input (libcst.codemod.tests.test_codemod_cli.TestCodemodCLI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\zsolz\LibCST\libcst\codemod\tests\test_codemod_cli.py", line 37, in test_codemod_formatter_error_input
    rlt.stderr.decode("utf-8"),
AssertionError: 'error: cannot format -: Cannot parse: 13:10:     async with AsyncExitStack() as stack:' not found in 'Calculating full-repo metadata...\r\nExecuting codemod...\r\n\r\x1b[2K0.02s 0% complete, [calculating] estimated for 1 files to go...\r\x1b[2KCodemodding C:\\Users\\zsolz\\LibCST\\libcst\\codemod\\tests\\codemod_formatter_error_input.py.txt\r\nFatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python\r\n\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\zsolz\\LibCST\\libcst\\codemod\\_cli.py", line 334, in _parallel_exec_process_stub\r\n    newcode = invoke_formatter(formatter_args, newcode)\r\n  File "C:\\Users\\zsolz\\LibCST\\libcst\\codemod\\_cli.py", line 63, in invoke_formatter\r\n    encoding=None if work_with_bytes else "utf-8",\r\n  File "C:\\Users\\zsolz\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\subprocess.py", line 376, in check_output\r\n    **kwargs).stdout\r\n  File "C:\\Users\\zsolz\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\subprocess.py", line 468, in run\r\n    output=stdout, stderr=stderr)\r\nsubprocess.CalledProcessError: Command \'[\'C:\\\\Users\\\\zsolz\\\\LibCST\\\\.tox\\\\py37\\\\Scripts\\\\black.exe\', \'-\']\' returned non-zero exit status 1.\r\n\r\nFailed to codemod C:\\Users\\zsolz\\LibCST\\libcst\\codemod\\tests\\codemod_formatter_error_input.py.txt\r\n\r\nFinished codemodding 1 files!\r\n - Transformed 0 files successfully.\r\n - Skipped 0 files.\r\n - Failed to codemod 1 files.\r\n - 0 warnings were generated.\r\n'
```

**Comment by jimmylai** [comment]
Currently we don't run tests on Windows. We can try use Github Actions and easily start running tests on different platforms (Windows, MacOS, Ubuntu).
