### ISSUE TITLE
Tests failing in the latest release

### ISSUE THREAD

**Issue by FFY00** [Instagram/LibCST#379]
```
$ pytest
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /build/python-libcst/src/LibCST-0.3.10
plugins: hypothesis-5.29.0
collected 1765 items

libcst/_nodes/tests/test_assert.py ..........                            [  0%]
libcst/_nodes/tests/test_assign.py ......................                [  1%]
libcst/_nodes/tests/test_atom.py ....................................... [  4%]
........................................................................ [  8%]
...................                                                      [  9%]
libcst/_nodes/tests/test_attribute.py .....                              [  9%]
libcst/_nodes/tests/test_await.py .........                              [  9%]
libcst/_nodes/tests/test_binary_op.py ................                   [ 10%]
libcst/_nodes/tests/test_boolean_op.py ........                          [ 11%]
libcst/_nodes/tests/test_call.py .................................       [ 13%]
libcst/_nodes/tests/test_classdef.py .......................             [ 14%]
libcst/_nodes/tests/test_comment.py ......                               [ 14%]
libcst/_nodes/tests/test_comparison.py .......................           [ 16%]
libcst/_nodes/tests/test_cst_node.py ............                        [ 16%]
libcst/_nodes/tests/test_del.py .....                                    [ 17%]
libcst/_nodes/tests/test_dict.py ...............                         [ 17%]
libcst/_nodes/tests/test_dict_comp.py .........                          [ 18%]
libcst/_nodes/tests/test_docstring.py ................                   [ 19%]
libcst/_nodes/tests/test_else.py ..                                      [ 19%]
libcst/_nodes/tests/test_empty_line.py .......                           [ 19%]
libcst/_nodes/tests/test_for.py ............                             [ 20%]
libcst/_nodes/tests/test_funcdef.py .................................... [ 22%]
........................................................                 [ 25%]
libcst/_nodes/tests/test_global.py ..........                            [ 26%]
libcst/_nodes/tests/test_if.py ........                                  [ 26%]
libcst/_nodes/tests/test_ifexp.py ......                                 [ 27%]
libcst/_nodes/tests/test_import.py ..................................... [ 29%]
...............                                                          [ 30%]
libcst/_nodes/tests/test_indented_block.py .............                 [ 30%]
libcst/_nodes/tests/test_lambda.py ..................................... [ 32%]
................                                                         [ 33%]
libcst/_nodes/tests/test_leaf_small_statements.py ...                    [ 33%]
libcst/_nodes/tests/test_list.py ..........                              [ 34%]
libcst/_nodes/tests/test_matrix_multiply.py ......                       [ 34%]
libcst/_nodes/tests/test_module.py .......................               [ 36%]
libcst/_nodes/tests/test_namedexpr.py ........                           [ 36%]
libcst/_nodes/tests/test_newline.py ......                               [ 36%]
libcst/_nodes/tests/test_nonlocal.py ..........                          [ 37%]
libcst/_nodes/tests/test_number.py .............                         [ 38%]
libcst/_nodes/tests/test_raise.py ................                       [ 39%]
libcst/_nodes/tests/test_removal_behavior.py ........                    [ 39%]
libcst/_nodes/tests/test_return.py ........                              [ 40%]
libcst/_nodes/tests/test_set.py ..........                               [ 40%]
libcst/_nodes/tests/test_simple_comp.py ............................     [ 42%]
libcst/_nodes/tests/test_simple_statement.py ........................... [ 43%]
                                                                         [ 43%]
libcst/_nodes/tests/test_simple_whitespace.py ..............             [ 44%]
libcst/_nodes/tests/test_small_statement.py ............                 [ 45%]
libcst/_nodes/tests/test_subscript.py .............................      [ 46%]
libcst/_nodes/tests/test_trailing_whitespace.py .....                    [ 47%]
libcst/_nodes/tests/test_try.py .......................                  [ 48%]
libcst/_nodes/tests/test_tuple.py ......................                 [ 49%]
libcst/_nodes/tests/test_unary_op.py ..........                          [ 50%]
libcst/_nodes/tests/test_while.py .........                              [ 50%]
libcst/_nodes/tests/test_with.py ................                        [ 51%]
libcst/_nodes/tests/test_yield.py ........................               [ 53%]
libcst/_parser/parso/tests/test_fstring.py ...                           [ 53%]
libcst/_parser/parso/tests/test_tokenize.py ............................ [ 54%]
.............                                                            [ 55%]
libcst/_parser/parso/tests/test_utils.py .....................           [ 56%]
libcst/_parser/tests/test_config.py .                                    [ 56%]
libcst/_parser/tests/test_detect_config.py .................             [ 57%]
libcst/_parser/tests/test_footer_behavior.py .......                     [ 58%]
libcst/_parser/tests/test_node_identity.py .                             [ 58%]
libcst/_parser/tests/test_parse_errors.py ............                   [ 58%]
libcst/_parser/tests/test_version_compare.py .................           [ 59%]
libcst/_parser/tests/test_whitespace_parser.py .........                 [ 60%]
libcst/_parser/tests/test_wrapped_tokenize.py ................           [ 61%]
libcst/_parser/types/tests/test_config.py ...........                    [ 61%]
libcst/codegen/tests/test_codegen_clean.py FFF                           [ 62%]
libcst/codemod/commands/tests/test_add_pyre_directive.py .......         [ 62%]
libcst/codemod/commands/tests/test_convert_format_to_fstring.py ........ [ 62%]
......                                                                   [ 63%]
libcst/codemod/commands/tests/test_convert_namedtuple_to_dataclass.py .. [ 63%]
......                                                                   [ 63%]
libcst/codemod/commands/tests/test_convert_percent_format_to_fstring.py . [ 63%]
..                                                                       [ 63%]
libcst/codemod/commands/tests/test_ensure_import_present.py .....        [ 64%]
libcst/codemod/commands/tests/test_fix_pyre_directives.py ..........     [ 64%]
libcst/codemod/commands/tests/test_noop.py .                             [ 64%]
libcst/codemod/commands/tests/test_remove_pyre_directive.py ..........   [ 65%]
libcst/codemod/commands/tests/test_remove_unused_imports.py ...........  [ 66%]
libcst/codemod/commands/tests/test_rename.py ........................... [ 67%]
.......                                                                  [ 67%]
libcst/codemod/commands/tests/test_strip_strings_from_types.py ........  [ 68%]
libcst/codemod/commands/tests/test_unnecessary_format_string.py .        [ 68%]
libcst/codemod/tests/test_cli.py .........                               [ 68%]
libcst/codemod/tests/test_codemod.py .xx.                                [ 69%]
libcst/codemod/tests/test_codemod_cli.py .                               [ 69%]
libcst/codemod/tests/test_metadata.py .                                  [ 69%]
libcst/codemod/tests/test_runner.py ....                                 [ 69%]
libcst/codemod/visitors/tests/test_add_imports.py ...................... [ 70%]
.                                                                        [ 70%]
libcst/codemod/visitors/tests/test_apply_type_annotations.py ........... [ 71%]
...........................                                              [ 72%]
libcst/codemod/visitors/tests/test_gather_comments.py ..                 [ 73%]
libcst/codemod/visitors/tests/test_gather_exports.py ..........          [ 73%]
libcst/codemod/visitors/tests/test_gather_imports.py .........           [ 74%]
libcst/codemod/visitors/tests/test_gather_string_annotation_names.py ... [ 74%]
...                                                                      [ 74%]
libcst/codemod/visitors/tests/test_gather_unused_imports.py .........    [ 75%]
libcst/codemod/visitors/tests/test_remove_imports.py ................... [ 76%]
...........                                                              [ 76%]
libcst/helpers/tests/test_expression.py ..............                   [ 77%]
libcst/helpers/tests/test_module.py .                                    [ 77%]
libcst/helpers/tests/test_statement.py ...............                   [ 78%]
libcst/helpers/tests/test_template.py ...........                        [ 79%]
libcst/matchers/tests/test_decorators.py ........................        [ 80%]
libcst/matchers/tests/test_extract.py ................                   [ 81%]
libcst/matchers/tests/test_findall.py ......                             [ 81%]
libcst/matchers/tests/test_matchers.py ................................  [ 83%]
libcst/matchers/tests/test_matchers_with_metadata.py .............       [ 84%]
libcst/matchers/tests/test_replace.py ...........                        [ 84%]
libcst/matchers/tests/test_visitors.py ................................. [ 86%]
.....                                                                    [ 86%]
libcst/metadata/tests/test_base_provider.py ..                           [ 87%]
libcst/metadata/tests/test_expression_context_provider.py .............. [ 87%]
.....                                                                    [ 88%]
libcst/metadata/tests/test_full_repo_manager.py ....                     [ 88%]
libcst/metadata/tests/test_metadata_provider.py ..........               [ 88%]
libcst/metadata/tests/test_metadata_wrapper.py .....                     [ 89%]
libcst/metadata/tests/test_parent_node_provider.py ...                   [ 89%]
libcst/metadata/tests/test_position_provider.py ...........              [ 90%]
libcst/metadata/tests/test_qualified_name_provider.py .......            [ 90%]
libcst/metadata/tests/test_reentrant_codegen.py .....                    [ 90%]
libcst/metadata/tests/test_scope_provider.py ........................... [ 92%]
...........                                                              [ 92%]
libcst/metadata/tests/test_span_provider.py .......                      [ 93%]
libcst/metadata/tests/test_type_inference_provider.py .                  [ 93%]
libcst/tests/test_batched_visitor.py ..                                  [ 93%]
libcst/tests/test_deep_clone.py .                                        [ 93%]
libcst/tests/test_deep_replace.py .....                                  [ 93%]
libcst/tests/test_exceptions.py .....                                    [ 94%]
libcst/tests/test_fuzz.py sss                                            [ 94%]
libcst/tests/test_pyre_integration.py .                                  [ 94%]
libcst/tests/test_tabs.py ........                                       [ 94%]
libcst/tests/test_tool.py ........                                       [ 95%]
libcst/tests/test_type_enforce.py ...................................... [ 97%]
.............................................                            [ 99%]
libcst/tests/test_visitor.py ..                                          [100%]

=================================== FAILURES ===================================
_____________ TestCodegenClean.test_codegen_clean_matcher_classes ______________

self = <libcst.codegen.tests.test_codegen_clean.TestCodegenClean testMethod=test_codegen_clean_matcher_classes>

    def test_codegen_clean_matcher_classes(self) -> None:
        """
        Verifies that codegen of matcher classes would not result in a
        changed file. If this test fails, please run 'tox -e codegen' to
        generate new files.
        """
        new_code = clean_generated_code("\n".join(matcher_codegen.generated_code))
        new_file = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "matcher_codegen.py.deleteme"
        )
        with open(new_file, "w") as fp:
            fp.write(new_code)
        try:
            format_file(new_file)
        except Exception:
            # We failed to format, but this is probably due to invalid code that
            # black doesn't like. This test will still fail and report to run codegen.
            pass
        with open(new_file, "r") as fp:
            new_code = fp.read()
        os.remove(new_file)
        with open(
            os.path.join(
                os.path.dirname(os.path.abspath(__file__)), "../../matchers/__init__.py"
            ),
            "r",
        ) as fp:
            old_code = fp.read()

        # Now that we've done simple codegen, verify that it matches.
>       self.assertTrue(
            old_code == new_code, "libcst.matchers.__init__ needs new codegen!"
        )
E       AssertionError: False is not true : libcst.matchers.__init__ needs new codegen!

libcst/codegen/tests/test_codegen_clean.py:81: AssertionError
_______________ TestCodegenClean.test_codegen_clean_return_types _______________

self = <libcst.codegen.tests.test_codegen_clean.TestCodegenClean testMethod=test_codegen_clean_return_types>

    def test_codegen_clean_return_types(self) -> None:
        """
        Verifies that codegen of return types would not result in a
        changed file. If this test fails, please run 'tox -e codegen' to
        generate new files.
        """
        new_code = clean_generated_code("\n".join(type_codegen.generated_code))
        new_file = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "type_codegen.py.deleteme"
        )
        with open(new_file, "w") as fp:
            fp.write(new_code)
        try:
            format_file(new_file)
        except Exception:
            # We failed to format, but this is probably due to invalid code that
            # black doesn't like. This test will still fail and report to run codegen.
            pass
        with open(new_file, "r") as fp:
            new_code = fp.read()
        os.remove(new_file)
        with open(
            os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "../../matchers/_return_types.py",
            ),
            "r",
        ) as fp:
            old_code = fp.read()

        # Now that we've done simple codegen, verify that it matches.
>       self.assertTrue(
            old_code == new_code, "libcst.matchers._return_types needs new codegen!"
        )
E       AssertionError: False is not true : libcst.matchers._return_types needs new codegen!

libcst/codegen/tests/test_codegen_clean.py:116: AssertionError
____________ TestCodegenClean.test_codegen_clean_visitor_functions _____________

self = <libcst.codegen.tests.test_codegen_clean.TestCodegenClean testMethod=test_codegen_clean_visitor_functions>

    def test_codegen_clean_visitor_functions(self) -> None:
        """
        Verifies that codegen of visitor functions would not result in a
        changed file. If this test fails, please run 'tox -e codegen' to
        generate new files.
        """
        new_code = clean_generated_code("\n".join(visitor_codegen.generated_code))
        new_file = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "visitor_codegen.py.deleteme"
        )
        with open(new_file, "w") as fp:
            fp.write(new_code)
        try:
            format_file(new_file)
        except Exception:
            # We failed to format, but this is probably due to invalid code that
            # black doesn't like. This test will still fail and report to run codegen.
            pass
        with open(new_file, "r") as fp:
            new_code = fp.read()
        os.remove(new_file)
        with open(
            os.path.join(
                os.path.dirname(os.path.abspath(__file__)), "../../_typed_visitor.py"
            ),
            "r",
        ) as fp:
            old_code = fp.read()

        # Now that we've done simple codegen, verify that it matches.
>       self.assertTrue(
            old_code == new_code, "libcst._typed_visitor needs new codegen!"
        )
E       AssertionError: False is not true : libcst._typed_visitor needs new codegen!

libcst/codegen/tests/test_codegen_clean.py:47: AssertionError
=============================== warnings summary ===============================
libcst/codemod/tests/test_metadata.py:15
  /build/python-libcst/src/LibCST-0.3.10/libcst/codemod/tests/test_metadata.py:15: PytestCollectionWarning: cannot collect test class 'TestingCollector' because it has a __init__ constructor (from: libcst/codemod/tests/test_metadata.py)
    class TestingCollector(ContextAwareVisitor):

libcst/codemod/tests/test_metadata.py:24
  /build/python-libcst/src/LibCST-0.3.10/libcst/codemod/tests/test_metadata.py:24: PytestCollectionWarning: cannot collect test class 'TestingTransform' because it has a __init__ constructor (from: libcst/codemod/tests/test_metadata.py)
    class TestingTransform(ContextAwareTransformer):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED libcst/codegen/tests/test_codegen_clean.py::TestCodegenClean::test_codegen_clean_matcher_classes
FAILED libcst/codegen/tests/test_codegen_clean.py::TestCodegenClean::test_codegen_clean_return_types
FAILED libcst/codegen/tests/test_codegen_clean.py::TestCodegenClean::test_codegen_clean_visitor_functions
====== 3 failed, 1757 passed, 3 skipped, 2 xfailed, 2 warnings in 31.46s =======
```

**Comment by FFY00** [comment]
This also fails with https://github.com/fedora-python/tox-current-env

```
$ tox -e py38 --current-env
py38 create: /build/python-libcst/src/LibCST-0.3.10/.tox/py38
py38 installed: apipkg==1.5,appdirs==1.4.4,attrs==20.1.0,black==19.10b0,CacheControl==0.12.6,chardet==3.0.4,click==7.1.2,colorama==0.4.3,contextlib2==0.6.0.post1,distlib==0.3.1,distro==1.5.0,filelock==3.0.12,html5lib==1.1,hypothesis==5.29.0,hypothesmith==0.1.4,idna==2.10,importlib-metadata==1.6.1,iniconfig==1.0.1,isort==5.4.2,lark-parser==0.9.0,libcst==0.3.9,more-itertools==8.4.0,msgpack==1.0.0,mypy-extensions==0.4.3,ordered-set==4.0.2,packaging==20.4,pathspec==0.8.0,pep517==0.8.2,pluggy==0.13.1,progress==1.5,py==1.9.0,pyparsing==2.4.7,pytest==6.0.1,pytest-runner==5.2,PyYAML==5.3.1,regex==2020.7.14,requests==2.24.0,resolvelib==0.4.0,retrying==1.3.3,six==1.15.0,sortedcontainers==2.2.2,toml==0.10.1,tox==3.19.0,tox-current-env==0.0.2,typed-ast==1.4.1,typing-extensions==3.7.4.3,typing-inspect==0.6.0,urllib3==1.25.10,virtualenv==20.0.23,webencodings==0.5.1,zipp==3.1.0
py38 run-test-pre: PYTHONHASHSEED='443052885'
py38 run-test: commands[0] | python -m unittest
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................FFF...........................................................................................................................xx.......................................................................................................................................................................................................................................................................................................................................................................................................................................................sss......................................................................................................
======================================================================
FAIL: test_codegen_clean_matcher_classes (libcst.codegen.tests.test_codegen_clean.TestCodegenClean)
Verifies that codegen of matcher classes would not result in a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-libcst/src/LibCST-0.3.10/libcst/codegen/tests/test_codegen_clean.py", line 81, in test_codegen_clean_matcher_classes
    self.assertTrue(
AssertionError: False is not true : libcst.matchers.__init__ needs new codegen!

======================================================================
FAIL: test_codegen_clean_return_types (libcst.codegen.tests.test_codegen_clean.TestCodegenClean)
Verifies that codegen of return types would not result in a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-libcst/src/LibCST-0.3.10/libcst/codegen/tests/test_codegen_clean.py", line 116, in test_codegen_clean_return_types
    self.assertTrue(
AssertionError: False is not true : libcst.matchers._return_types needs new codegen!

======================================================================
FAIL: test_codegen_clean_visitor_functions (libcst.codegen.tests.test_codegen_clean.TestCodegenClean)
Verifies that codegen of visitor functions would not result in a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-libcst/src/LibCST-0.3.10/libcst/codegen/tests/test_codegen_clean.py", line 47, in test_codegen_clean_visitor_functions
    self.assertTrue(
AssertionError: False is not true : libcst._typed_visitor needs new codegen!

----------------------------------------------------------------------
Ran 1765 tests in 25.198s

FAILED (failures=3, skipped=3, expected failures=2)
ERROR: InvocationError for command /build/python-libcst/src/LibCST-0.3.10/.tox/py38/bin/python -m unittest (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py38: commands failed
```

**Comment by FFY00** [comment]
Fixed in the latest release.
