### ISSUE TITLE
Parse error on star expressions in f-strings

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#387]
```
❯ cat test.py
x = [1, 2]
print(f"List of: {*x,}")
❯ python3 test.py
List of: (1, 2)
❯ libcst print test.py
Traceback (most recent call last):
  File "python3.7/site-packages/fbcode/libcst/_parser/base_parser.py", line 152, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: ReservedString(*)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "python3.7/site-packages/fbcode/libcst/tool.py", line 832, in <module>
    main(os.environ.get("LIBCST_TOOL_COMMAND_NAME", "libcst.tool"), sys.argv[1:])
  File "python3.7/site-packages/fbcode/libcst/tool.py", line 827, in main
    return lookup.get(args.action or None, _invalid_command)(proc_name, command_args)
  File "python3.7/site-packages/fbcode/libcst/tool.py", line 277, in _print_tree_impl
    else PartialParserConfig()
  File "python3.7/site-packages/fbcode/libcst/_parser/entrypoints.py", line 76, in parse_module
    detect_default_newline=True,
  File "python3.7/site-packages/fbcode/libcst/_parser/entrypoints.py", line 51, in _parse
    result = parser.parse()
  File "python3.7/site-packages/fbcode/libcst/_parser/base_parser.py", line 111, in parse
    self._add_token(token)
  File "python3.7/site-packages/fbcode/libcst/_parser/base_parser.py", line 191, in _add_token
    raw_column=token.start_pos[1],
libcst._exceptions.ParserSyntaxError: Syntax Error @ 2:19.
Incomplete input. Unexpectedly encountered '*'.

print(f"List of: {*x,}")
                  ^
```

**Comment by jimmylai** [comment]
Similar to the other missing comprehension parsing in f-string. This is caused by missing `star_expr` support in `fstring_expr`.

**Comment by taylorhughes** [comment]
Also seen with: f"\N{DOUBLE EXCLAMATION MARK} Foobar" -- a subset of the named emoji strings we have are causing this, guessing they are missing on this system's emoji set or something.

**Comment by thatch** [comment]
@taylorhughes your last comment about named escapes is https://github.com/davidhalter/parso/issues/154 in parso.

@zsol I think the original bug is basically the same as #416 and the PR for that also fixed this one.  taylor's still exists, do you want to close and file a new one to track an upstream fix?

**Comment by zsol** [comment]
There's #400 for the one @taylorhughes mentions. Let's close this. Thx for the fix!
