### ISSUE TITLE
AttributeError: 'Import' object has no attribute 'visit'

### ISSUE THREAD

**Issue by shelbyladallen** [Instagram/LibCST#438]
When running the following:

```
with open(pythonfile, "rb") as pf:
	pf_read = pf.read()
	cst_node = cst.parse_module(pf_read)
	purifier = PurifierTransformer(src_func_purity_dict)
	cst_node_purified = cst_node.visit(purifier)
```

I get:

```
Traceback (most recent call last):
  File "libcst_pure.py", line 83, in <module>
    check_pure(args.pythonfile, args.w)
  File "libcst_pure.py", line 68, in check_pure
    cst_node_purified = cst_node.visit(purifier)
  File "/Users/my_user/.virtualenvs/my_proj/lib/python3.7/site-packages/libcst/_nodes/module.py", line 91, in visit
    result = super(Module, self).visit(visitor)
  File "/Users/my_user/.virtualenvs/my_proj/lib/python3.7/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/Users/my_user/.virtualenvs/my_proj/lib/python3.7/site-packages/libcst/_nodes/module.py", line 75, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/Users/my_user/.virtualenvs/my_proj/lib/python3.7/site-packages/libcst/_nodes/internal.py", line 200, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/Users/my_user/.virtualenvs/my_proj/lib/python3.7/site-packages/libcst/_nodes/internal.py", line 172, in visit_body_iterable
    new_child = child.visit(visitor)
AttributeError: 'Import' object has no attribute 'visit'
```

What confuses me is that:
- I've tried to match the reading/parsing/tranforming paradigm in the docs as exactly as possible
- my input has no import statements, and I've confirmed that cst_node is a module object.

Thoughts on possible versioning mismatch? I'm almost certain that I'm passing the right object type into the right libcst function. Any feedback? Thanks!

**Comment by shelbyladallen** [comment]
I'm realizing this has something to do with my transformer, as a visitor doesn't do this. closing. thanks.
