### ISSUE TITLE
Support PEP 622 pattern matching syntax

### ISSUE THREAD

**Issue by tirkarthi** [Instagram/LibCST#487]
https://www.python.org/dev/peps/pep-0622/

```
from dataclasses import dataclass

@dataclass
class Person:
    name: str

    
person = Person("Kate")

match person:
    case Person(name):
        print(f"Found {name}")
    case _:
        print("Not found")
```

```
python -m libcst.tool print /tmp/dataclass_match.py
/root/py310-venv/lib/python3.10/site-packages/libcst/tool.py:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
Traceback (most recent call last):
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 152, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(NAME)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/tool.py", line 832, in <module>
    main(os.environ.get("LIBCST_TOOL_COMMAND_NAME", "libcst.tool"), sys.argv[1:])
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/tool.py", line 827, in main
    return lookup.get(args.action or None, _invalid_command)(proc_name, command_args)
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/tool.py", line 272, in _print_tree_impl
    tree = parse_module(
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 71, in parse_module
    result = _parse(
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 51, in _parse
    result = parser.parse()
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 111, in parse
    self._add_token(token)
  File "/root/py310-venv/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 187, in _add_token
    raise ParserSyntaxError(
libcst._exceptions.ParserSyntaxError: Syntax Error @ 10:7.
Incomplete input. Encountered 'person', but expected ';', or 'NEWLINE'.

match person:
      ^
```

**Comment by zsol** [comment]
This depends on #285

**Comment by zsol** [comment]
This should work as of version `0.4.1` (as long as the `LIBCST_PARSER_TYPE` env var is set to `native`)
