### ISSUE TITLE
Rust parser fails on trailing indentation

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#572]
Repro by @tushar-deepsource:

```pycon
Python 3.10.0
>>> import libcst
>>> code = '''\
... if x == type(y):
...     pass
...     ''' # This indent whitespace is important
>>> libcst.parse_statement(code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../libcst/_parser/entrypoints.py", line 138, in parse_statement
    result = _parse(
  File ".../libcst/_parser/entrypoints.py", line 55, in _parse
    return parse(source_str)
libcst._exceptions.ParserSyntaxError: Syntax Error @ 3:5.
parser error: error at 3:4: expected one of (, *, +, -, ..., AWAIT, DEDENT, False, NAME, NUMBER, None, True, [, break, continue, lambda, match, not, pass, ~

    pass
       ^
>>>
```

_Originally posted by @tushar-deepsource in https://github.com/Instagram/LibCST/issues/568#issuecomment-1002574953_

**Comment by zsol** [comment]
This is handled in the pure parser by automatically appending a newline here:
https://github.com/Instagram/LibCST/blob/c44ff0500b52dd78716c36c7d1efd3016e20005f/libcst/_parser/detect_config.py#L161-L171

which gets removed in https://github.com/Instagram/LibCST/blob/c44ff0500b52dd78716c36c7d1efd3016e20005f/libcst/_nodes/module.py#L109

Unfortunately this hack doesn't really work well unless `parse_module` is used, and then `code` is called on the returned `Module` object, which is why I decided not to port the hack over to Rust. Instead, the Rust tokenizer adds a fake newline token automatically without mutating the input (this is important because the Rust API's `String` input is immutable)
https://github.com/Instagram/LibCST/blob/c44ff0500b52dd78716c36c7d1efd3016e20005f/native/libcst/src/tokenizer/core/mod.rs#L337-L344
And then during inflation (i.e. whitespace parsing) this fake newline is detected here:
https://github.com/Instagram/LibCST/blob/c44ff0500b52dd78716c36c7d1efd3016e20005f/native/libcst/src/tokenizer/whitespace_parser.rs#L248-L253
