### ISSUE TITLE
`ParserSyntaxError` on Parenthesized with-as statement.

### ISSUE THREAD

**Issue by tushar-deepsource** [Instagram/LibCST#580]
It seems there is partial support for parenthesized with statements, but `with-as` doesn't work in it.

It is reproducible on both native and pure python parsers. Using libcst v0.4.0a1.

## Reproduction

```console
$ export LIBCST_PARSER_TYPE=none
$ python
Python 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcst
>>> _ = libcst.parse_module('with (x, y): pass')
>>> _ = libcst.parse_module('with x as a, y as b: pass')
>>> _ = libcst.parse_module('with (x as a): pass')
Traceback (most recent call last):
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 151, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: ReservedString(as)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 56, in _parse
    return _pure_python_parse(
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 89, in _pure_python_parse
    result = parser.parse()
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 110, in parse
    self._add_token(token)
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/base_parser.py", line 186, in _add_token
    raise ParserSyntaxError(
libcst._exceptions.ParserSyntaxError: Syntax Error @ 1:9.
Incomplete input. Encountered 'as', but expected ')'.

with (x as a): pass
        ^
>>> 

$ export LIBCST_PARSER_TYPE=native
$ python
Python 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcst
>>> libcst._parser.entrypoints.is_native()
True
>>> _ = libcst.parse_module('with (x, y): pass')
>>> _ = libcst.parse_module('with x as a, y as b: pass')
>>> _ = libcst.parse_module('with (x as a): pass')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
  File "/Users/tusharsadhwani/code/marvin-python/venv3/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 55, in _parse
    return parse(source_str)
libcst._exceptions.ParserSyntaxError: Syntax Error @ 1:12.
parser error: error at 1:11: expected one of !=, %, &, (, ), *, **, +, -, ., /, //, :=, <, <<, <=, ==, >, >=, >>, @, ASYNC, [, ^, and, for, if, in, is, not, or, |

with (x as a): pass
           ^
>>> 
```

**Comment by zsol** [comment]
Thanks for the bug report! The pure python parser will not support this, but I'll take a look at the native one soon.

**Comment by stroxler** [comment]
I'm hoping to add native parser support this week
