### ISSUE TITLE
Test failures in CI

### ISSUE THREAD

**Issue by stroxler** [Instagram/LibCST#671]
It looks like CI broke without any relevant changes in LibCST - my guess is that some change in pypi is responsible for the breakage.

The failures look like this:

```
 ======================================================================
FAIL: test_codemod_formatter_error_input (libcst.codemod.tests.test_codemod_cli.TestCodemodCLI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/LibCST/LibCST/libcst/codemod/tests/test_codemod_cli.py", line 37, in test_codemod_formatter_error_input
    self.assertIn(
AssertionError: 'error: cannot format -: Cannot parse: 13:10:     async with AsyncExitStack() as stack:' not found in 'Calculating full-repo metadata...\nExecuting codemod...\nFailed to determine module name for /home/runner/work/LibCST/LibCST/libcst/codemod/tests/codemod_formatter_error_input.py.txt: \'/home/runner/work/LibCST/LibCST/libcst/codemod/tests/codemod_formatter_error_input.py.txt\' is not in the subpath of \'/home/runner/work/LibCST/LibCST/libcst/tests/pyre\' OR one path is relative and the other is absolute.\nTraceback (most recent call last):\n  File "/opt/hostedtoolcache/Python/3.9.12/x64/bin/black", line 8, in <module>\n    sys.exit(patched_main())\n  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/black/__init__.py", line 1322, in patched_main\n    patch_click()\n  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/black/__init__.py", line 1308, in patch_click\n    from click import _unicodefun\nImportError: cannot import name \'_unicodefun\' from \'click\' (/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/click/__init__.py)\n\r\x1b[2KCodemodding /home/runner/work/LibCST/LibCST/libcst/codemod/tests/codemod_formatter_error_input.py.txt\n\nTraceback (most recent call last):\n  File "/home/runner/work/LibCST/LibCST/libcst/codemod/_cli.py", line 311, in _execute_transform\n    newcode = invoke_formatter(config.formatter_args, newcode)\n  File "/home/runner/work/LibCST/LibCST/libcst/codemod/_cli.py", line 56, in invoke_formatter\n    subprocess.check_output(\n  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/subprocess.py", line 424, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/subprocess.py", line 528, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/opt/hostedtoolcache/Python/3.9.12/x64/bin/black\', \'-\']\' returned non-zero exit status 1.\n\nFailed to codemod /home/runner/work/LibCST/LibCST/libcst/codemod/tests/codemod_formatter_error_input.py.txt\n\n\r\x1b[2K0.41s 0% complete, [calculating] estimated for 1 files to go...\r\x1b[2KFinished codemodding 1 files!\n - Transformed 0 files successfully.\n - Skipped 0 files.\n - Failed to codemod 1 files.\n - 0 warnings were generated.\n'
```
which looks like black failing under the hood.

**Comment by stroxler** [comment]
My first guess was that maybe a new black version was causing these problems, but black didn't actually change.

After processing the dependency downloads for Python 3.9 tests comparing the last successful CI run to the latest failing ones, these are the differences I found:
```
<   Downloading bleach-4.1.0-py2.py3-none-any.whl (157 kB)
---
>   Downloading bleach-5.0.0-py3-none-any.whl (160 kB)
145c146
<   Downloading click-8.0.4-py3-none-any.whl (97 kB)
---
>   Downloading click-8.1.2-py3-none-any.whl (96 kB)
154a156
>   Downloading fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
157c159
<   Downloading hypothesis-6.39.4-py3-none-any.whl (378 kB)
---
>   Downloading hypothesis-6.41.0-py3-none-any.whl (380 kB)
162,163c164,165
<   Downloading ipykernel-6.9.2-py3-none-any.whl (130 kB)
<   Downloading ipython-8.1.1-py3-none-any.whl (750 kB)
---
>   Downloading ipykernel-6.12.1-py3-none-any.whl (130 kB)
>   Downloading ipython-8.2.0-py3-none-any.whl (750 kB)
170c172
<   Downloading jupyter_client-7.1.2-py3-none-any.whl (130 kB)
---
>   Downloading jupyter_client-7.2.2-py3-none-any.whl (130 kB)
187,188c189,190
<   Downloading nbconvert-6.4.4-py3-none-any.whl (561 kB)
<   Downloading nbformat-5.2.0-py3-none-any.whl (74 kB)
---
>   Downloading nbconvert-6.4.5-py3-none-any.whl (561 kB)
>   Downloading nbformat-5.3.0-py3-none-any.whl (73 kB)
190c192
<   Downloading nest_asyncio-1.5.4-py3-none-any.whl (5.1 kB)
---
>   Downloading nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
200,201c202,203
<   Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
<   Downloading prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
---
>   Downloading prometheus_client-0.14.0-py3-none-any.whl (59 kB)
>   Downloading prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
217c219
<   Downloading qtconsole-5.2.2-py3-none-any.whl (120 kB)
---
>   Downloading qtconsole-5.3.0-py3-none-any.whl (120 kB)
223c225
<   Downloading setuptools-61.0.0-py3-none-any.whl (1.1 MB)
---
>   Downloading setuptools-62.0.0-py3-none-any.whl (1.1 MB)
230c232
<   Downloading soupsieve-2.3.1-py3-none-any.whl (37 kB)
---
>   Downloading soupsieve-2.3.2-py3-none-any.whl (37 kB)
246c248
<   Downloading tomlkit-0.10.0-py3-none-any.whl (33 kB)
---
>   Downloading tomlkit-0.10.1-py3-none-any.whl (34 kB)
```

I know for a fact that `click` changes caused test suites to break for several tools (including pyre-check) so my initial hunch is to start looking there.
