### ISSUE TITLE
Fails to parse parenthesized `with` statement without trailing comma

### ISSUE THREAD

**Issue by andersk** [Instagram/LibCST#855]
#584 added parenthesized `with` statements to the native parser, but they’re only accepted when a trailing comma is present. Python accepts them with or without a trailing comma.

```console
$ pip freeze
libcst==0.4.9
mypy-extensions==0.4.3
PyYAML==6.0
typing-inspect==0.8.0
typing_extensions==4.4.0

$ export LIBCST_PARSER_TYPE=native

$ python3 -c 'import libcst; libcst.parse_statement("with (a as a, b as b,): pass")'

$ python3 -c 'import libcst; libcst.parse_statement("with (a as a, b as b): pass")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/v/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 138, in parse_statement
    result = _parse(
  File "/tmp/v/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 55, in _parse
    return parse(source_str)
libcst._exceptions.ParserSyntaxError: Syntax Error @ 1:1.
parser error: error at 1:20: expected *

with (a as a, b as b): pass
^
```

Cc @stroxler

**Comment by jakkdl** [comment]
I'm hitting this as well in https://github.com/Zac-HD/flake8-trio
It additionally also fails with newlines:
```python
with (
    open("a") as a,
    open("b") as b,
):
    pass
```
```python
$ python3.11 -c 'import libcst; libcst.parse_module("with (\n    open(a) as a,\n    open(b) as b,\n):\n    pass\n")' 
Traceback (most recent call last):
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/base_parser.py", line 151, in _add_token
    plan = stack[-1].dfa.transitions[transition]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ReservedString(as)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
             ^^^^^^^
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/entrypoints.py", line 56, in _parse
    return _pure_python_parse(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/entrypoints.py", line 89, in _pure_python_parse
    result = parser.parse()
             ^^^^^^^^^^^^^^
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/base_parser.py", line 110, in parse
    self._add_token(token)
  File "/home/h/Git/flake8-trio/.venv/lib/python3.11/site-packages/libcst/_parser/base_parser.py", line 186, in _add_token
    raise ParserSyntaxError(
libcst._exceptions.ParserSyntaxError: Syntax Error @ 2:13.
Incomplete input. Encountered 'as', but expected ')'.

    open(a) as a,
            ^
```

**Comment by stroxler** [comment]
Thanks for the bug reports - I'll try to tackle this in the next week.

**Comment by jakkdl** [comment]
oh I'm sorry, mine is due to not having done `LIBCST_PARSER_TYPE=native`
